In [1]:
import zeus21
from matplotlib import pyplot as plt
import numpy as np
import scipy
from scipy.interpolate import interp1d,InterpolatedUnivariateSpline
from matplotlib.gridspec import GridSpec
import matplotlib.lines as mlines
#set up the CLASS cosmology
from classy import Class
ClassCosmo = Class()
ClassCosmo.compute()

import sys
sys.path.append('../21cm_ETHOS/21cmFAST-ethos-analysis-main/')
import sheth_tormen as st

from astropy.cosmology import FlatLambdaCDM
from astropy.cosmology import Planck15 as P15
from astropy import constants as const
import astropy.units as u
import h5py


In [2]:

CosmoParams_input = zeus21.Cosmo_Parameters_Input()
ClassyCosmo = zeus21.runclass(CosmoParams_input)
parcos = zeus21.Cosmo_Parameters(CosmoParams_input,ClassyCosmo)

corrf = zeus21.Correlations(parcos,ClassyCosmo)
parastro = zeus21.Astro_Parameters(parcos)

dictest = {}

def linspace(start, stop, step=1.):

  return np.linspace(start, stop, int((stop - start) / step + 1))

data = linspace(1, 10)
data2 = linspace(1, 10)

for i in range(len(data)):
    for j in range(len(data2)):
        y = linspace(0,data[i]+data2[j])
        dictest.update({(data[i],data2[j]):y})

       

In [3]:
dictest = {}

h_peak = [0.2,0.5]
k_peak = [50,100]#[1.7,2]

for i in range(len(h_peak)):
    for j in range(len(k_peak)):
        y = zeus21.HMF_interpolator(parcos, ClassyCosmo,LCDM=False, logk=True, h_peak=h_peak[i],k_peak=k_peak[j])
        dictest.update({(h_peak[i],k_peak[j]):y})

In [4]:
zeus21.HMF_interpolator(parcos, ClassyCosmo,LCDM=False)

In [5]:
dictest

{(0.2, 50): <zeus21.cosmology.HMF_interpolator at 0x7fc6402432b0>,
 (0.2, 100): <zeus21.cosmology.HMF_interpolator at 0x7fc620a7a050>,
 (0.5, 50): <zeus21.cosmology.HMF_interpolator at 0x7fc6401549d0>,
 (0.5, 100): <zeus21.cosmology.HMF_interpolator at 0x7fc658be7f10>}

In [6]:
dictest[0.5,100]

In [7]:
T21_coeff = zeus21.get_T21_coefficients(parcos, ClassyCosmo, parastro, dictest[0.5,100], zmin=10)
powerspec21 = zeus21.Power_Spectra(parcos, ClassCosmo, corrf, T21_coeff, RSD_MODE=1)

In [8]:
klist = powerspec21.klist_PS
zlist = T21_coeff.zintegral

In [9]:
kchoose=0.121
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=18.1892;
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

In [10]:
_ik

30

In [11]:
klist[_ik]

0.11547230876763816

In [12]:
zlist[_iz]

18.158502122237405

In [13]:
zrange = np.array([27.4, 23.4828, 20.5152, 18.1892, 16.3171, 14.7778, 13.4898, \
12.3962, 11.4561, 10.6393, 9.92308])

z_range_center = []

for i in range(1,len(zrange)):
    z_range_center.append((zrange[i-1]-zrange[i])/2+zrange[i])

In [14]:
z_range_center

[25.4414,
 21.999000000000002,
 19.3522,
 17.253149999999998,
 15.54745,
 14.1338,
 12.943000000000001,
 11.92615,
 11.047699999999999,
 10.28119]

In [15]:
krange = np.array([0.1, 0.11, 0.121, 0.1331, 0.14641, 0.161051, 0.177156, \
0.194872, 0.214359, 0.235795, 0.259374, 0.285312, 0.313843, 0.345227, \
0.37975, 0.417725, 0.459497, 0.505447, 0.555992, 0.611591, 0.67275, \
0.740025, 0.814027, 0.89543, 0.984973, 1.08347, 1.19182, 1.311, \
1.4421])

k_range_center = []

for i in range(1,len(krange)):
   k_range_center.append((krange[i-1]-krange[i])/2+krange[i])

In [16]:
k_range_center

[0.10500000000000001,
 0.11549999999999999,
 0.12705,
 0.13975500000000002,
 0.1537305,
 0.16910350000000002,
 0.186014,
 0.2046155,
 0.225077,
 0.24758449999999999,
 0.272343,
 0.2995775,
 0.329535,
 0.3624885,
 0.39873749999999997,
 0.438611,
 0.482472,
 0.5307195,
 0.5837915,
 0.6421705,
 0.7063875,
 0.777026,
 0.8547285,
 0.9402014999999999,
 1.0342215,
 1.137645,
 1.25141,
 1.37655]

In [17]:
iz_list = []

for j in range(len(z_range_center)):
    iz_list.append(min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-z_range_center[j])))

iz_list

[47, 40, 33, 27, 22, 17, 13, 9, 5, 1]

In [18]:
for i in range(len(iz_list)):
    print(zlist[iz_list[i]])

25.46197181625777
22.15338158551349
19.2747175754866
17.106927664800104
15.487881441501974
14.02206616209623
12.949947541484711
11.959802456254806
11.045363259922468
10.200841526428455


In [19]:
ik_list = []

for j in range(len(k_range_center)):
    ik_list.append(min(range(len(klist)), key=lambda i: np.abs(klist[i]-k_range_center[j])))



In [20]:
for i in range(len(ik_list)):
    print(klist[ik_list[i]])

0.09563411636162635
0.11547230876763816
0.11547230876763816
0.1394257049619067
0.1394257049619067
0.16834795641994382
0.20326979475208332
0.20326979475208332
0.24543576493132385
0.24543576493132385
0.29634857840484286
0.29634857840484286
0.3578226667460024
0.3578226667460024
0.4320488443926624
0.4320488443926624
0.5216723849233917
0.5216723849233917
0.6298872933550222
0.6298872933550222
0.760550134139035
0.760550134139035
0.9183174714605349
0.9183174714605349
1.1088118199391528
1.1088118199391528
1.3388220198853236
1.3388220198853236


In [21]:
powerspec21.Deltasq_T21[_iz]

array([3.53428726e-06, 7.26550157e-06, 1.54222409e-05, 3.17409273e-05,
       6.70512486e-05, 1.37964365e-04, 2.89065785e-04, 5.92406934e-04,
       1.22636297e-03, 2.48878954e-03, 5.06125064e-03, 1.00854292e-02,
       1.99628934e-02, 3.85594085e-02, 7.31568113e-02, 1.34141747e-01,
       2.37629698e-01, 3.99729497e-01, 6.34435786e-01, 9.34687449e-01,
       1.27649130e+00, 1.62449770e+00, 1.99243807e+00, 2.45180348e+00,
       3.10607350e+00, 3.96773125e+00, 4.75242042e+00, 5.05944292e+00,
       5.88311803e+00, 6.99058672e+00, 7.26063835e+00, 8.45954532e+00,
       9.14611724e+00, 9.98342709e+00, 1.09939812e+01, 1.20298054e+01,
       1.31789916e+01, 1.43794794e+01, 1.55780379e+01, 1.67381561e+01,
       1.77398318e+01, 1.82865418e+01, 1.81431886e+01, 1.69183683e+01,
       1.43913642e+01])

In [22]:
powerspec21.Deltasq_T21[:,_ik]

array([9.62678980e+00, 9.76435692e+00, 9.98841659e+00, 1.03345484e+01,
       1.08581745e+01, 1.16116555e+01, 1.26464615e+01, 1.39950066e+01,
       1.56239425e+01, 1.74167033e+01, 1.90876192e+01, 2.01865339e+01,
       2.01464578e+01, 1.85051135e+01, 1.52304841e+01, 1.10707387e+01,
       7.55578103e+00, 6.53205585e+00, 9.23944110e+00, 1.56189009e+01,
       2.40455172e+01, 3.23024894e+01, 3.81343136e+01, 4.02434475e+01,
       3.87279836e+01, 3.43284834e+01, 2.82427690e+01, 2.18132162e+01,
       1.59286813e+01, 1.10156257e+01, 7.26063835e+00, 4.58549510e+00,
       2.78537454e+00, 1.63051515e+00, 9.20721775e-01, 5.02994194e-01,
       2.66246823e-01, 1.36697793e-01, 6.81053112e-02, 3.29270449e-02,
       1.54446169e-02, 7.02419904e-03, 3.09503275e-03, 1.32009038e-03,
       5.44572382e-04, 2.17050562e-04, 8.34803333e-05, 3.09443274e-05,
       1.10405342e-05, 3.78592581e-06, 1.24594510e-06, 3.92853808e-07,
       1.18433547e-07, 3.40542396e-08, 9.33804024e-09, 2.43700558e-09,
      

In [23]:
obs_PS21 = np.ndarray((len(iz_list), len(ik_list)))

for i in range(len(ik_list)):
    for j in range(len(iz_list)):


       obs_PS21[j,i] =powerspec21.Deltasq_T21[iz_list[j],ik_list[i]]

In [24]:
np.shape(obs_PS21)

(10, 28)

In [25]:
np.shape(powerspec21.Deltasq_T21)

(64, 45)

In [26]:
len(zlist)

64

In [27]:
len(klist)

45

In [28]:
len(iz_list)

10

In [29]:
len(ik_list)

28

In [30]:
powerspec21.Deltasq_T21[_iz,_ik]

7.2606383548820705

In [31]:
ik_list

[29,
 30,
 30,
 31,
 31,
 32,
 33,
 33,
 34,
 34,
 35,
 35,
 36,
 36,
 37,
 37,
 38,
 38,
 39,
 39,
 40,
 40,
 41,
 41,
 42,
 42,
 43,
 43]

In [32]:
print(z_range_center[5])
print(k_range_center[11])

14.1338
0.2995775


In [33]:
ki = 11
zi = 5

kchoose=k_range_center[ki]
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=z_range_center[zi]
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

print(powerspec21.Deltasq_T21[_iz,_ik])
print(obs_PS21[zi,ki])

54.75535839501544
54.75535839501544


In [34]:
ki = 18
zi = 5

kchoose=k_range_center[ki]
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=z_range_center[zi]
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

print(powerspec21.Deltasq_T21[_iz,_ik])
print(obs_PS21[zi,ki])

144.78004200962067
144.78004200962067


In [35]:
ki = 1
zi = 7
kchoose=k_range_center[ki]
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=z_range_center[zi]
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

print(powerspec21.Deltasq_T21[_iz,_ik])
print(obs_PS21[zi,ki])

17.41670326572958
17.41670326572958


In [36]:
def obs_PS(klist,zlist,PS,krange,zrange):
    
    z_range_center = np.ndarray(len(zrange)-1)
    k_range_center = np.ndarray(len(krange)-1)
    iz_list = []
    ik_list = []

    
    for i in range(len(z_range_center)):
        z_range_center[i]=(zrange[i]-zrange[i+1])/2+zrange[i+1]

    for i in range(len(k_range_center)):
        k_range_center[i]=(krange[i]-krange[i+1])/2+krange[i+1]
                              
    for j in range(len(z_range_center)):
        iz_list.append(min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-z_range_center[j])))
    for j in range(len(k_range_center)):
        ik_list.append(min(range(len(klist)), key=lambda i: np.abs(klist[i]-k_range_center[j])))

    obs_PS21 = np.ndarray((len(iz_list), len(ik_list)))

    for i in range(len(ik_list)):
        for j in range(len(iz_list)):


            obs_PS21[j,i] = PS[iz_list[j],ik_list[i]]

    
    return obs_PS21

In [37]:
obs = obs_PS(klist,zlist,powerspec21.Deltasq_T21,krange,zrange)

In [38]:
ki = 10
zi = 7
kchoose=k_range_center[ki]
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=z_range_center[zi]
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

print(powerspec21.Deltasq_T21[_iz,_ik])
print(obs_PS21[zi,ki])

23.79016215897687
23.79016215897687


In [39]:
    z_range_center2 = np.ndarray(len(zrange)-1)
    k_range_center = np.ndarray(len(krange)-1)
    iz_list = []
    ik_list = []

    
    for i in range(len(z_range_center2)):
        z_range_center2[i]=(zrange[i]-zrange[i+1])/2+zrange[i+1]

In [40]:
z_range_center2

array([25.4414 , 21.999  , 19.3522 , 17.25315, 15.54745, 14.1338 ,
       12.943  , 11.92615, 11.0477 , 10.28119])

In [41]:
z_range_center

[25.4414,
 21.999000000000002,
 19.3522,
 17.253149999999998,
 15.54745,
 14.1338,
 12.943000000000001,
 11.92615,
 11.047699999999999,
 10.28119]

In [43]:
zeus21.Power_Spectra_Obs(powerspec21.Deltasq_T21, klist,zlist,krange,zrange).z_center_value

array([25.4414 , 21.999  , 19.3522 , 17.25315, 15.54745, 14.1338 ,
       12.943  , 11.92615, 11.0477 , 10.28119])

In [45]:
zeus21.Power_Spectra_Obs(powerspec21.Deltasq_T21, klist,zlist,krange,zrange).k_center_value

array([0.105    , 0.1155   , 0.12705  , 0.139755 , 0.1537305, 0.1691035,
       0.186014 , 0.2046155, 0.225077 , 0.2475845, 0.272343 , 0.2995775,
       0.329535 , 0.3624885, 0.3987375, 0.438611 , 0.482472 , 0.5307195,
       0.5837915, 0.6421705, 0.7063875, 0.777026 , 0.8547285, 0.9402015,
       1.0342215, 1.137645 , 1.25141  , 1.37655  ])

In [50]:
obs_ps21cm = zeus21.Power_Spectra_Obs(powerspec21.Deltasq_T21, klist,zlist,krange,zrange)

In [51]:

obs_ps21cm.PS21

array([[2.95687932e-05, 3.09443274e-05, 3.09443274e-05, 3.59062498e-05,
        3.59062498e-05, 3.89772019e-05, 4.28387158e-05, 4.28387158e-05,
        4.78116529e-05, 4.78116529e-05, 5.33195443e-05, 5.33195443e-05,
        5.94938487e-05, 5.94938487e-05, 6.65950675e-05, 6.65950675e-05,
        7.43308139e-05, 7.43308139e-05, 8.21236633e-05, 8.21236633e-05,
        8.91826577e-05, 8.91826577e-05, 9.37379507e-05, 9.37379507e-05,
        9.32507390e-05, 9.32507390e-05, 8.49382739e-05, 8.49382739e-05],
       [1.48778182e-02, 1.54446169e-02, 1.54446169e-02, 1.78511060e-02,
        1.78511060e-02, 1.92501689e-02, 2.10170522e-02, 2.10170522e-02,
        2.32665851e-02, 2.32665851e-02, 2.56386234e-02, 2.56386234e-02,
        2.82591005e-02, 2.82591005e-02, 3.12553899e-02, 3.12553899e-02,
        3.43429524e-02, 3.43429524e-02, 3.74022511e-02, 3.74022511e-02,
        4.01258079e-02, 4.01258079e-02, 4.16547239e-02, 4.16547239e-02,
        4.10825391e-02, 4.10825391e-02, 3.73339175e-02, 3.73339

In [62]:
ki = 25
zi = 6
kchoose=obs_ps21cm.k_center_value[ki]
_ik = min(range(len(klist)), key=lambda i: np.abs(klist[i]-kchoose))
zchoose=obs_ps21cm.z_center_value[zi]
_iz = min(range(len(zlist)), key=lambda i: np.abs(zlist[i]-zchoose))

print(powerspec21.Deltasq_T21[_iz,_ik])
print(obs_PS21[zi,ki])
print(obs_ps21cm.PS21[zi,ki])

177.05601169401626
177.05601169401626
177.05601169401626
