In [3]:
import zeus21
from matplotlib import pyplot as plt
import numpy as np
import scipy
from scipy.interpolate import interp1d,InterpolatedUnivariateSpline
from matplotlib.gridspec import GridSpec
import matplotlib.lines as mlines
#set up the CLASS cosmology
from classy import Class
ClassCosmo = Class()
ClassCosmo.compute()

import sys
sys.path.append('../21cm_ETHOS/21cmFAST-ethos-analysis-main/')
import sheth_tormen as st

from astropy.cosmology import FlatLambdaCDM
from astropy.cosmology import Planck15 as P15
from astropy import constants as const
import astropy.units as u



In [4]:
omega_cdm = 0.12
CosmoParams_input = zeus21.Cosmo_Parameters_Input(omegac = omega_cdm)
ClassyCosmo = zeus21.runclass(CosmoParams_input)
parcos = zeus21.Cosmo_Parameters(CosmoParams_input,ClassyCosmo)

dictest = {}

def linspace(start, stop, step=1.):

  return np.linspace(start, stop, int((stop - start) / step + 1))

data = linspace(1, 10)
data2 = linspace(1, 10)

for i in range(len(data)):
    for j in range(len(data2)):
        y = linspace(0,data[i]+data2[j])
        dictest.update({(data[i],data2[j]):y})

       

In [119]:
dictest = {}

h_peak = [0.2,0.3]
k_peak = [50,100]#[1.7,2]

for i in range(len(h_peak)):
    for j in range(len(k_peak)):
        y = zeus21.HMF_interpolator(parcos, ClassyCosmo,LCDM=False, logk=True, h_peak=h_peak[i],k_peak=k_peak[j])
        dictest.update({(h_peak[i],k_peak[j]):y})

In [149]:
h_peak_ethos = np.linspace(0.25,1,16)
h_peak = np.array([0,0.2])
h_peak = np.concatenate((h_peak,h_peak_ethos), axis=None)
k_peak = np.logspace(1.5,2,108)

In [143]:
h_peak

array([0.  , 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65,
       0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [150]:
k_peak

array([ 31.6227766 ,  32.03450204,  32.45158811,  32.87410459,
        33.3021222 ,  33.73571256,  34.17494822,  34.61990268,
        35.07065041,  35.52726683,  35.98982835,  36.45841237,
        36.93309731,  37.41396261,  37.90108872,  38.39455717,
        38.89445053,  39.40085245,  39.91384767,  40.43352204,
        40.95996252,  41.4932572 ,  42.03349533,  42.5807673 ,
        43.13516471,  43.69678031,  44.26570809,  44.84204325,
        45.42588225,  46.01732277,  46.61646378,  47.22340555,
        47.83824965,  48.46109895,  49.0920577 ,  49.73123146,
        50.3787272 ,  51.03465327,  51.69911944,  52.37223689,
        53.05411826,  53.74487766,  54.44463068,  55.15349442,
        55.87158749,  56.59903006,  57.33594387,  58.08245222,
        58.83868003,  59.60475386,  60.38080189,  61.16695399,
        61.96334172,  62.77009833,  63.58735884,  64.41525999,
        65.25394034,  66.10354023,  66.96420182,  67.83606914,
        68.71928809,  69.61400646,  70.52037398,  71.43

In [144]:
dic_hmf = {}


for i in range(len(h_peak)):
    for j in range(len(k_peak)):
        y = zeus21.HMF_interpolator(parcos, ClassyCosmo,LCDM=False, h_peak=h_peak[i],k_peak=k_peak[j])
        dictest.update({(h_peak[i],k_peak[j]):y})

In [145]:
dictest

{(0.2, 50): <zeus21.cosmology.HMF_interpolator at 0x7fede1188040>,
 (0.2, 100): <zeus21.cosmology.HMF_interpolator at 0x7fedcb91e8f0>,
 (0.3, 50): <zeus21.cosmology.HMF_interpolator at 0x7fede11890c0>,
 (0.3, 100): <zeus21.cosmology.HMF_interpolator at 0x7fede3aa0580>,
 (0.0,
  31.622776601683793): <zeus21.cosmology.HMF_interpolator at 0x7fedf147dcc0>,
 (0.0,
  33.59818286283783): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a6950>,
 (0.0,
  35.69698846826064): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a7e80>,
 (0.0,
  37.926901907322495): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a7790>,
 (0.0, 40.296113202004): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a6ad0>,
 (0.0,
  42.81332398719393): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a6da0>,
 (0.0,
  45.48777947003777): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a7610>,
 (0.0,
  48.32930238571752): <zeus21.cosmology.HMF_interpolator at 0x7fedf19a7c70>,
 (0.0,
  51.34832907437552): <zeus21.cosmology.HMF_interpola

In [155]:
h_peak_ethos = np.linspace(0.25,1,16)
h_peak = np.array([0,0.2])
h_peak = np.concatenate((h_peak,h_peak_ethos), axis=None)
k_peak = np.linspace(30,300,271)

In [156]:
k_peak

array([ 30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,
        41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,
        52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,
        63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,
        74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
        85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,
        96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106.,
       107., 108., 109., 110., 111., 112., 113., 114., 115., 116., 117.,
       118., 119., 120., 121., 122., 123., 124., 125., 126., 127., 128.,
       129., 130., 131., 132., 133., 134., 135., 136., 137., 138., 139.,
       140., 141., 142., 143., 144., 145., 146., 147., 148., 149., 150.,
       151., 152., 153., 154., 155., 156., 157., 158., 159., 160., 161.,
       162., 163., 164., 165., 166., 167., 168., 169., 170., 171., 172.,
       173., 174., 175., 176., 177., 178., 179., 18

In [157]:
dic_hmf = {} #hpeak 0-1 in 0.05 steps - kpeak 30-300

for i in range(len(h_peak)):
    for j in range(len(k_peak)):
        y = zeus21.HMF_interpolator(parcos, ClassyCosmo,LCDM=False, h_peak=h_peak[i],k_peak=k_peak[j])
        dic_hmf.update({(h_peak[i],k_peak[j]):y})

In [173]:
dic_hmf[0.35,30]